### ISSUE TITLE
ip-based rate limiting

### ISSUE THREAD

**Issue by dajohi** [decred/vspd#11]

**Comment by dajohi** [comment]
should be failure based.  as long as the client sends good data, the rate limit does not apply.

**Comment by jholdstock** [comment]
We should discuss letting specialised webserver software (eg. nginx) handle this - no need to re-invent the wheel here. We could provide a sample webserver config file, similar to [dcrstakepool](https://github.com/decred/dcrstakepool/blob/master/sample-nginx.conf).

It would add extra burden to admins, but admins should be pretty comfortable with webserver software anyway.

**Comment by jholdstock** [comment]
Closing this one - see the previous comment. nginx (or similar) should be used for this.
