### ISSUE TITLE
[url] Add API version into URL request

### ISSUE THREAD

**Issue by vctt94** [decred/vspd#118]
Older versions of vspd have the API version into the request, for example: `/api/v1/getpurchaseinfo`, but right now this new version does not have it, example: `/api/vspinfo`.

We should call it `/api/v3/vspinfo` to keep consistency.

**Comment by jholdstock** [comment]
Agree that vspd API routes should include a version number, however I don't think we should start at v3. vspd is a new piece of software and its API should start at v1. This is not version 3 of the dcrstakepool API, its version 1 of the vspd API. 

This highlights that we need to consider how we distinguish dcrstakepool and vspd in dcrwebapi - 
https://api.decred.org/?c=gsd
However that is a seperate problem

**Comment by jholdstock** [comment]
related: decred/dcrwebapi#98
