### ISSUE TITLE
Different rpc cert for each voting wallet

### ISSUE THREAD

**Issue by jholdstock** [decred/vspd#162]
At the moment the same cert is used for each wallet

**Comment by xaur** [comment]
```
wallethost = 127.0.0.1:20111,127.0.0.1:20112
walletuser = user1,user2
walletpass = pass1,pass2
walletcert = rpc1.cert,rpc2.cert
```

@jholdstock re #163, four manually synchronized lists is a room for error, esp. for operators having 5+ voting wallets. Would it be possible to use JSON-based config to accomodate the need to store lists of objects?

Alternatively (if that is too big of a change), INI sections would still be better than these manually synced lists, e.g. see how it works in Firefox [profiles.ini](http://kb.mozillazine.org/Profiles.ini_file) file:

```
[Wallet1]
wallethost = 127.0.0.1:20111
walletuser = user1
walletpass = pass1
walletcert = rpc1.cert

[Wallet2]
wallethost = 127.0.0.1:20112
walletuser = user2
walletpass = pass2
walletcert = rpc2.cert
```

**Comment by jholdstock** [comment]
One of the main reasons I implemented this approach is that dcrstakepool worked in this way, so it should be something which is already familiar to VSP operators. I'm keen to keep the upgrade from dcrstakepool to vspd as straightforward and familiar as possible.

I like the .ini sections idea, but as mentioned, that would be a new thing for VSP operators to learn. And besides, we don't have anything to detect sections dynamically atm - the section names are hard-coded.

**Comment by xaur** [comment]
I see, minimizing transition barriers is reasonable.

How about this. In the initial vspd release: accept old-style configs, mark it as deprecated, add new-style section-based configs. And then remove the old-style configs in a few releases? This will start the transition sooner. Same keys under different sections should not conflict with each others.

What do you think, would the cleaner config syntax and reduced room for error outweigh writing new code and maintaining both styles during the transition?
