### ISSUE TITLE
status endpoint returning 404

### ISSUE THREAD

**Issue by isuldor** [decred/vspd#175]
While initially setting up vspd I confirmed that the `/status` endpoint was returning a HTTP 200, even with nginx in front of it. Today while I was wiring up a health check monitor all I could get was a 404 error. I've tried running master and also rolling back to the first build, but all versions I have reproduced the issue.

```
curl http://localhost:8800/status
404 page not found

curl http://localhost:8800/api/v3/status
404 page not found
```

This is while that the `/admin/status` endpoint is working fine when using `curl --user admin:password`, and I don't see any other issues

**Comment by isuldor** [comment]
I may just be mis-remembering that /status worked, rather I saw that a /status endpoint exists in webapi.go.  I figured it was the easiest check. It's probably better to use the /admin/status endpoint for a health check anyway.

**Comment by jholdstock** [comment]
The current state of the API is this: 

```
GET /admin/status        
- health-check endpoint for sysadmins - requires basic auth

GET /api/v3/vspinfo      
- public VSP info for populating pages such as decred.org/vsp and Decrediton

POST /api/v3/ticketstatus
- information about a specific ticket - requires ticket auth
```

`/status` has never been used afaict - I think you may have mis-remembered. Going to close this one for now, but feel free to re-open if you have any problems with the endpoints I've listed above.
