### ISSUE TITLE
txindex not enabled

### ISSUE THREAD

**Issue by Sirmorrison** [decred/vspd#181]
When i run VSPD, i keep getting the prompt on terminal that dcrd connection error: dcrd does not have transaction index enabled(--txindex)
<img width="566" alt="image" src="https://user-images.githubusercontent.com/27733432/90967633-e8068900-e4d9-11ea-8e40-605afcb4b475.png">

However i have this option set on my dcrd config file and also pass this as a parameter to the dcrd command.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/27733432/90967626-b8f01780-e4d9-11ea-9c88-345eedec3fc7.png">

is there something i am doing wrong?

**Comment by jholdstock** [comment]
The installer will have given you the latest release version - 1.5.1. vspd requires dcrd and dcrwallet from master.

It is strange that you got the txindex error though, you should really have gotten an error about an incorrect dcrd API version. I will look into that

**Comment by jholdstock** [comment]
Trying to recreate on my machine:

```
❯ ./dcrd --version
dcrd version 1.5.1+release (Go version go1.13.7 linux/amd64)
```

vspd says no
```
2020-08-24 09:39:33.043 [ERR]  BG: dcrd connect error: dcrd has incompatible JSON-RPC version: got 6.1.1, expected 6.1.2
```

Maybe your vspd is also a bit behind master?

**Comment by Sirmorrison** [comment]
Hummmm. So to get around this i will need to work with dcrd and dcrwallet from master.

**Comment by jholdstock** [comment]
I still cannot recreate this using vspd master, neither using dcrd master nor dcrd 1.5.2.

Unless you can provide further details on how to recreate this problem, this issue will be closed.

**Comment by Sirmorrison** [comment]
The issue is not on master
