### ISSUE TITLE
Registering tickets with invalid vote choices should be possible

### ISSUE THREAD

**Issue by jholdstock** [decred/vspd#197]
At the moment an error is returned if the client vote options do not match the servers

**Comment by xaur** [comment]
@jholdstock can you please elaborate a bit why invalid vote choises should be allowed? And is there a mechanism to warn the user about that?

**Comment by jholdstock** [comment]
The flow for decrediton is

1. buy tickets
2. get fee address from vspd
3. pay fee to provided address

If the vsp returns an "invalid vote choice" error on step 3, the wallet user needs to take recovery steps:

- If the choice is invalid because decrediton is out of date, the user needs to update their wallet and retry registering the tickets with the vsp.
- If the choice is invalid because the server is out of date, the user either needs to bug the VSP operator to update, or they need to re-register their tickets with another VSP.

All the while - their tickets are not registered with any VSP and are at risk of being missed.

Allowing invalid vote choices removes all of the above UX friction, whilst introducing zero/minimal risks/compromises.

**Comment by jholdstock** [comment]
I dont think we have any need for warnings or notifications on this. If a user wishes to vote on an upcoming agenda, they will need to update their dcrwallet/decrediton before they are able to set their vote preferences, otherwise the wallet will not have the new agenda listed.

**Comment by xaur** [comment]
Thanks for elaborating! I agree the user will likely have updated wallet to vote on latest agendas. What about server, what happens if the server is out of date in this case?

**Comment by xaur** [comment]
Oh and another question, does vspd (and dcrstakepool) have a field in their status endpoints to report the "vote choice" version (consensus version?) they are running that we could possibly show at the [VSPs](https://decred.org/vsp/) listing to ensure that VSPs are upgrading?
