### ISSUE TITLE
admin view with more informations

### ISSUE THREAD

**Issue by karamble** [decred/vspd#203]
I would like to see further information on the admin page.

- Immature Tickets
- Able to list registered Tickets and scroll trough. Listviews Decrediton alike with further information (blockheight, age in days, fees paid) would be optimal

**Comment by isuldor** [comment]
> Able to list registered Tickets and scroll trough

dcrwallet can already show you this on any of your voting nodes: `dcrctl --wallet gettickets 1`. I rather like how vspd itself has moved towards just being an api rather than a user facing GUI app. That's the wallets job.

**Comment by jholdstock** [comment]
One of the initial design goals for the vspd front-end was to use no JavaScript at all. Unfortunately, implementing an infinite scroll or paginated list is not feasible without JS.

Personally I am open to adding JavaScript to enable features like this, with the proviso that the JavaScript remains as minimal as possible and **completely** optional.

**Comment by ukane-philemon** [comment]
@jholdstock is this feature still a priority?

**Comment by jholdstock** [comment]
I don't think so. No desire for this shown by other VSP admins, and there is a workaround using dcrctl.

**Comment by ukane-philemon** [comment]
Alright, thanks for your feedback.
