### ISSUE TITLE
api rpc with a secret request for admin only with wallet status

### ISSUE THREAD

**Issue by karamble** [decred/vspd#204]
an 'getinfo' api request for admins would be nice. This should only be able to be requested in combination with a secret to enable access for admins and monitoring purposes only.

-List of wallets (id, ip, wallet status, blockheight, amount of tix)

**Comment by jholdstock** [comment]
https://github.com/decred/vspd/blob/master/docs/deployment.md#voting-wallet-status

I think this covers what you are looking for.

**Comment by karamble** [comment]
Where is my mind?
The only missed info i would request at this point is the amount of tickets for each of these wallets. Since the wallets are set on manualtickets i can query these trough rpc via: 'dcrctl --wallet ticketinfo 499000 | jq '. | length' but having the information of the registered tickets for each individual wallet in your api endpoint would really help on the operational side. Not sure if these could pottentially become out of sync at all and if this would need monitoring.

**Comment by jholdstock** [comment]
The number of live tickets on each of the voting wallets is not a useful thing to measure for monitoring, the values will rarely be the same.

When one ticket is added to multiple wallets, and the ticket is called to vote, the wallets race to broadcast the vote. Only one of the wallets will succeed, the others will receive errors like `tx already exists`. The successful wallet will update the ticket status from `live` to `voted`, but it will remain with status `live` on the other voting wallets.

So long as vspd can connect to the voting wallets, it will always ensure they all have all of the correct tickets. Monitoring the connectivity is enough.

**Comment by jholdstock** [comment]
Closing for the reasons above
