### ISSUE TITLE
show vsp proportion

### ISSUE THREAD

**Issue by vctt94** [decred/vspd#206]
The old vsp show us the vsp proportion of the pool and we should show it on this new vsp, as well:

![image](https://user-images.githubusercontent.com/15069783/99593203-0fcd9600-29d0-11eb-8d06-0500e77000c8.png)

**Comment by jholdstock** [comment]
In dcrstakepool this is achieved by pulling the information from dcrwebapi using JavaScript. Right now, dcrwebapi is not providing the data for vspd, so we would need changes there.

See [this comment](https://github.com/decred/vspd/issues/203#issuecomment-730298314) for more info on JS.
