### ISSUE TITLE
Improve ticket iterations & lookups

### ISSUE THREAD

**Issue by dnldd** [decred/vspd#223]
The criteria for ticket equality according to `InsertNewTicket` requires that the ticket hash as well as the fee address and the fee address index are identical. Tickets in the database are currently keyed by only their hashes however, requiring each ticket in the database being unmarshalled just for fee address and fee address index comparisons when checking for duplicates on inserting a new ticket into the database. I suggest using a composite key comprising of the fee address index, fee address and the ticket hash: `<fee address index><fee address><ticket hash>`. This composite key mitigates unmarshalling all tickets for comparison purposes when inserting a new ticket since all comparison data can be extracted from the key. 

If there are no objections I'd like to start making the necessary modifications and upgrade the database.

**Comment by jholdstock** [comment]
Firstly, just to clarify, the check is not 

```
(ticketHash matches) AND (feeAddr matches) AND (feeAddrIdx matches)
```

it is actually

```
(ticketHash matches) OR (feeAddr matches) OR (feeAddrIdx matches)
```

So if the keys were changed, we would still have to iterate over every key to make the checks. It wouldn't be as simple as just checking one key. It is correct that this would remove the need to unmarshal every ticket though.

That said, I'm not fully convinced that this optimisation is worth the code complexity required for a database upgrade. `InsertNewTicket` is called infrequently, and json unmarshalling is cheap. 

Let me think aloud about this...

If every single ticket is given to one VSP, `InsertNewTicket` will be called 5 times per block, so approx once per minute on average. In the real world, ~50% of tickets are solo, and there are >10 VSPs, so a more realistic estimate is more like once every 15-20 minutes.

I guess we have to consider that a bunch of tickets may be added in a burst, but that shouldn't be happening too often, and the bursts won't be **massive**.

It might be interesting to write up some code to benchmark how long it takes to unmarshal a huge number of tickets, and see if the result is actually a concern or not.

**Comment by dnldd** [comment]
Thanks for the clarification on the check. Iterating over keys with boltdb is pretty fast and that will still be needed with the suggested change. The unmarshal calls through a ticket dataset that is growing over time is the issue I'm looking to eliminate. With the keys updated to house all the detail needed for the checks the unmarshal call would no longer be required. I agree the call by itself isn't costly, I think the growing dataset of tickets will over time make it so.  I'll get the suggested benchmark done.

**Comment by dnldd** [comment]
```sh
goos: linux
goarch: amd64
pkg: github.com/decred/vspd/database
Benchmark1KTicketUnmarshals-8     	     278	   3933861 ns/op	  376002 B/op	    4000 allocs/op
Benchmark5KTicketUnmarshals-8     	      64	  19761755 ns/op	 1880008 B/op	   20000 allocs/op
Benchmark10KTicketUnmarshals-8    	      32	  38075283 ns/op	 3760026 B/op	   40000 allocs/op
Benchmark100KTicketUnmarshals-8   	       3	 391093136 ns/op	37600010 B/op	  400000 allocs/op
PASS
ok  	github.com/decred/vspd/database	6.745s
```

These were generated from:
```go
func Benchmark1KTicketUnmarshals(b *testing.B) {
	count := 1000 // update accordingly
	tickets := make([][]byte, 0, count)
	for idx := 0; idx < count; idx++ {
		tb, err := json.Marshal(Ticket{})
		if err != nil {
			panic(err)
		}
		tickets = append(tickets, tb)
	}

	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		for idx := 0; idx < count; idx++ {
			var t Ticket
			err := json.Unmarshal(tickets[idx], &t)
			if err != nil {
				panic(err)
			}
		}
	}
}
```

**Comment by jholdstock** [comment]
I've spent some time on this with dnldd and there definitely are some issues with database scaling. Will post some more info shortly.

**Comment by jholdstock** [comment]
#241 removes the fee address index from the uniqueness checks, so if we choose to extend the database keys they will only need to be `Ticket Hash + Fee Address`

**Comment by jholdstock** [comment]
I have expanded on the benchmark code provided above to include writing to a real bolt database file.

The time taken to insert a new ticket scales linearly with the number of tickets in the database. Using the current strategy of storing tickets as JSON encoded strings in a single bucket, the insertion time reaches 1 second when the DB contains ~80k tickets, and 2 seconds at around ~160k tickets.

The suggestion above to add the fee address to the DB key helps to make insertions more performant, however it does not help in other places where iterating over all tickets is needed - eg. `filterTickets` and `CountTickets`. In those cases, we still need to JSON decode every ticket.

To improve performance for both insertions and iterations, I have instead tried storing each ticket as its own bucket. This increases the size of the database but dramatically improves performance.

The following stats are from databases which contain ~200k tickets:

|                  | JSON Encoding | Bucket per ticket |
|------------------|---------------|-------------------|
| DB Size          | 352 MB        | 824 MB            |
| InsertNewTicket  | 2.5 Seconds   | 0.65 seconds      |
| CountTickets     | 2.40 Seconds  | 0.32 Seconds      |

The graph shows how insertion time scales, blue using JSON encoding, orange is a bucket per ticket:

![insert_benchmark](https://user-images.githubusercontent.com/6762864/116717834-3eb15480-a9d1-11eb-824f-08c5fae4c796.png)

**Comment by jholdstock** [comment]
Benchmarking code: https://pastebin.com/6WJPuuNp

**Comment by jholdstock** [comment]
- Validated that key length makes no difference to database disk usage. Previously we used short keys because they were JSON encoded and contributed to increasing disk usage. Now we can use long, descriptive keys.
- Running on https://testnet-vsp.jholdstock.uk (database contains ~15k tickets). Memory usage and upgrade duration negligible.
- Used benchmark code from #223 to test a database containing ~200k tickets:
    - Old code
        - InsertNewTicket 2.39s
        - CountAllTickets 2.41s
    - New code
        - InsertNewTicket 0.30s
        - CountAllTickets 0.27s 

**Ready for review**
