### ISSUE TITLE
Cannot pay ticket fee

### ISSUE THREAD

**Issue by infertux** [decred/vspd#225]
vspd returns gibberish to Decrediton which cannot pay the ticket fee.

Here is the relevant vspd log output: `[WRN] VSPC: server response has differing request: []byte{0x7b, 0x22, 0x74, 0x69, [...]`

The regression bug was most likely introduced in commit https://github.com/decred/vspd/commit/ac8e20f3c1dbd2702924d490a8891894608634fe @jholdstock 

See @jrick comment for proposed fix: https://github.com/decred/vspd/pull/220#issuecomment-760284441

**Comment by jrick** [comment]
We've actually decided on a different fix, which is to keep that vspd patch, but also patch dcrwallet to unmarshal into a []byte.  this way we are sending a base64 encoding of the request over the wire (i was wrong, it is not marshaled into a json array), which cannot be mangled during encoding or decoding.

see decred/dcrwallet#1963.

**Comment by jrick** [comment]
With that dcrwallet pr merged, there's nothing left to change in vspd.
