### ISSUE TITLE
Fee tx already received

### ISSUE THREAD

**Issue by feeleep75** [decred/vspd#235]
Not sure if this is an error but it looks like Decredition keeps asking vspd about ticket every couple of minutes (sometimes even few seconds). Why not tell to client only once that ticket has been confirmed and stop spamming?

**Comment by jholdstock** [comment]
This message is logged when a client is making an invalid request - eg. requesting a fee address or attempting to pay a fee when a fee has already been paid. If the request is being spammed it is a client issue (decrediton or dcrwallet) and not a server issue.
