### ISSUE TITLE
Add block height to vspinfo response

### ISSUE THREAD

**Issue by jholdstock** [decred/vspd#252]
This seems like it should be trivial to add, and it would be useful for determining if a VSP is forked off of the network for some reason. I just cant remember why this wasn't already added, and if there is a good reason not to do it.

**Comment by xaur** [comment]
If this is added, it would be useful to expose it in dcrwebapi similar to https://github.com/decred/dcrwebapi/issues/136

**Comment by jholdstock** [comment]
Checked back over some old emails and chats, I did discuss this idea briefly with dhill last year. There isn't really a good reason not to do this, but it should be noted that there are actually 4+ different block heights which could be reported - the instance of dcrd used by vspd, and three voting wallets.
