### ISSUE TITLE
webapi: Consider querying the chain for the relay fee.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/vspd#283]
https://github.com/decred/vspd/blob/e42b1cad330596c243baf4c391dc40c981f4de90/webapi/getfeeaddress.go#L52-L55

`estimatefee` or `estimatesmartfee` (difference?) could be used to get a more accurate idea of what the current fee is. 0.0001 can be used as fallback for when `estimatesmartfee` errors.

ATM I don't think this matters much, but it may some day.

**Comment by jholdstock** [comment]
Relevant history for this: #54 #256

The hard-coded value is only ever used for passing into the func `txrules.StakePoolTicketFee` (provided by dcrwallet) to calculate the fee for adding a ticket to the VSP. The value is never used for constructing/broadcasting transactions.

Discussed this with @jrick and came to the conclusion that hard-coding is fine.

**Comment by JoeGruffins** [comment]
I guess the fee isn't ever involved in a transaction? I guess it was needed before when fee was part of the ticket purchase?

Closing. Sorry to bring up an old issue.
