### ISSUE TITLE
Return alternate signing address in /ticketstatus response

### ISSUE THREAD

**Issue by jholdstock** [decred/vspd#306]
https://github.com/decred/vspd/blob/master/docs/api.md#ticket-status

@JoeGruffins do you think this is important? Could maybe be useful for recovering from error scenarios, or restoring a wallet from seed?

**Comment by JoeGruffins** [comment]
Sorry slow to respond to this. The user will know their alternate signing address based on the commitment address, so I don't think it is necessary.
