### ISSUE TITLE
RPC Connection to wallet

### ISSUE THREAD

**Issue by dabuchera** [decred/vspd#316]
Hi all,
Searching for some answers here...
`[ERR] RPC: dcrwallet connection error: dial tcp XXX.XXX.XXX.XXX:19110: connect: connection timed out`
Ty

**Comment by jholdstock** [comment]
Opening issues on GitHub is not the proper way to seek help for your personal deployment problems, GitHub is for tracking and coordinating development work.

Please join one of our chat platforms (preferably https://chat.decred.org) where we will be happy to help.
