### ISSUE TITLE
Protocol spec

### ISSUE THREAD

**Issue by xaur** [decred/vspd#377]
I encountered a few references to the "original vspd spec" (latest in https://github.com/decred/dcrwallet/pull/2213) and thought maybe it should live in this repo, similar to the one in [dcrdex repo](https://github.com/decred/dcrdex/tree/d0697ebf5e1a0511623ccade1356933f07bf3448/spec)?

It looks like a good amount of VSP behavior is already captured in [api.md](https://github.com/decred/vspd/blob/3bb2f651511815c359c08990072bbcf235108ff3/docs/api.md) and [two-way-accountability.md](https://github.com/decred/vspd/blob/3bb2f651511815c359c08990072bbcf235108ff3/docs/two-way-accountability.md) so maybe there is nothing else to do. But just in case, it might be worth checking if anything can be pulled from https://github.com/decred/dcrstakepool/issues/574 - the only document I remember being referred to as "spec". There may be more notes/docs elsewhere ofc.

**Comment by jholdstock** [comment]
I think your are right in saying "there is nothing else to do", those two docs capture everything afaict

**Comment by xaur** [comment]
To check if anything is missing I read [api.md](https://github.com/decred/vspd/blob/3bb2f651511815c359c08990072bbcf235108ff3/docs/api.md), [two-way-accountability.md](https://github.com/decred/vspd/blob/3bb2f651511815c359c08990072bbcf235108ff3/docs/two-way-accountability.md), and then https://github.com/decred/dcrstakepool/issues/574 looking for things not mentioned in the first two.

First of all I appreciate the new docs. They are easy to read, explain what's going on pretty well and I can imagine writing a custom client with them, so they work as a "spec" for me.

Overall all important stuff is covered. I noted a few points not (explicitly) mentioned in the new docs, listed below.

1\. Motivation and improvements over dcrstakepool

> solve the privacy issues associated with VSP accounts, while simultaneously removing the VSP fees from tickets themselves, making it possible for both solo and VSP stakers to purchase mixed tickets in the same anonymity set.

Not critical for using the docs and the API but could help for general understanding what was driving the design (ability to mix in the same anon set, redeem scripts, maybe other).

2\. Key derivation stuff.

> For this design, a new purpose key should be used, since these keys are used differently from normal wallet accounts, and handling should be logically and hierarchically separated. A new purpose key of 565350 is chosen (565350 is the UTF-8 encoding of "VSP", as hex).

This and any other references of accoutns, branches, "purpose key" etc. I'm not sure if this is used in the current implementation or if it belongs to vspd docs, i.e. something vspd is concerned about vs being dcrwallet internals.

3\. The bit about constructing signatures

> This requires signing a message (which should be constructed in a way that prevents the signature from being used for unintended purposes) with the commitment address' key.

Same as (2), not sure vspd is concerned about this or if it should be in the docs.

4\. Timestamped receipts

> A timestamped receipt is returned by the server that commits to the ticket and the voting preferences. \[or to any other data received from the client\]

Looks like "timestamped receipt" is is implemented by `VSP-Client-Signature` HTTP client request header, `VSP-Server-Signature` server response header, and the `timestamp` field in requests and responses (`timestamp` is signed along the other fields). So this is done and covered by the docs.

5\. Storing audit trail

I guess the original idea was for client and server to store all comms between each other locally (for a reasonable duration, e.g. until the ticket is voted?), and optionally anchoring to a blockchain or a transparent log system. In case this is not implemented it could be mentioned as a possible future upgrade.

**Comment by xaur** [comment]
Great, with #380 branched off we can close this with #381. Thank you!
