### ISSUE TITLE
hot-swapping the fees xpub on an existing VSP

### ISSUE THREAD

**Issue by artikozel** [decred/vspd#461]
What would the desirable flow be if a VSP operator , for one reason or another, needed to retire or simply lost control of or access to a wallet that was used to initialise the vspd database?
Would re-initialising the vspd database with a different xpub meant to generate addresses for users to send fees to result in the creation of an essentially new VSP and completely erase the track record and history of the existing VSP?

**Comment by jholdstock** [comment]
The only way to change the xpub currently is to create an entirely new database, which essentially means a totally new VSP. All history, and the keypair used to sign requests/responses, would be lost.

Whilst it's totally possible to add code for xpub changing, the vspd daemon isn't the right place to implement it. Thinking about this problem has inspired #465.
