### ISSUE TITLE
[dcrd] Check for rpc version match

### ISSUE THREAD

**Issue by vctt94** [decred/vspd#94]
When running vspd, if the dcrwallet rpc mismatch versions, for example, an error will be thrown: 

`2020-06-01 16:56:36.104 [ERR] VSP: dcrwallet client error: dcrwallet 'wss://127.0.0.1:19110/ws' has wrong RPC version: got 8.0.0, expected 8.1.0`

It looks like the same does not happen for dcrd, but it would be a good check.

**Comment by jholdstock** [comment]
Related decred/dcrd#2207

**Comment by jholdstock** [comment]
vspd already checks for a specific API version.

Per Dave's comment in #2207 - RPC version has already been incremented for this dcrd release cycle.

Nothing to do here, closing.
